From r-base:3.6.0

RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list

RUN apt-get -y update 
## if adding this, we can gather the 2 apt-get lines but the size of the image goes from 3.65Go to 4.2Go
#&& apt-get dist-upgrade -y
RUN apt-get -y install libxml2-dev python-pip python-dev git libcairo2-dev libxt-dev xorg openbox software-properties-common openssl libcurl4-openssl-dev libssl-dev wget net-tools default-jre default-jdk time curl python3-pip 
RUN apt-get -y install libtool bison flex

#install Python3 packages
RUN python3 -m pip install 'cmake==3.13.3'; python3 -m pip install numpy scipy h5py leidenalg 'numba==0.47.0' umap-learn scikit-learn pandas matplotlib MulticoreTSNE

#install HDF5
RUN wget -O hdf5.tar.gz http://gecftools.epfl.ch/share/fab/hdf5-1.10.6-linux-centos7-x86_64-shared.tar.gz; tar -zxf hdf5.tar.gz
#RUN tar -zxf hdf5.tar.gz
ENV LD_LIBRARY_PATH=/hdf5-1.10.6-linux-centos7-x86_64-gcc485-shared/lib/
ENV PATH=$PATH:/hdf5-1.10.6-linux-centos7-x86_64-gcc485-shared/bin
RUN cd /hdf5-1.10.6-linux-centos7-x86_64-shared/bin && ./h5redeploy -force && cd / && rm hdf5.tar.gz && rm -rf hdf5-1.10.6-linux-centos7-x86_64-shared

#Install R packages

RUN Rscript -e "install.packages(c('BiocManager'), repos='http://stat.ethz.ch/CRAN/'); \
BiocManager::install(c('multtest'), version = '3.10'); \
install.packages(c('R6', 'bit64', 'Rtsne', 'jsonlite', 'data.table', 'devtools', 'flexmix', 'rPython', 'statmod', 'plotly', 'future.apply', 'Seurat'), repos='http://stat.ethz.ch/CRAN/'); \
devtools::install_github(c('grimbough/rhdf5','tallulandrews/M3Drop')); \
BiocManager::install(c('sva', 'DESeq2', 'limma', 'cluster', 'Cairo', 'scater', 'SC3', 'XVector'), version = '3.10');"

#RUN python3 -m pip uninstall umap-learn; python3 -m pip install 'umap-learn==0.3.7'
#RUN pip install numpy scipy h5py leidenalg 'numba==0.42.0' scikit-learn umap-learn
#uninstall
#RUN python3 -m pip uninstall -y  leidenalg 'numba==0.42.0' umap-learn MulticoreTSNE

ENV USER=rvmuser USER_ID=1006 USER_GID=1006
# now creating user NO NEED IN LAST INSTALL
RUN groupadd --gid "${USER_GID}" "${USER}" && \
    useradd \
      --uid ${USER_ID} \
      --gid ${USER_GID} \
      --create-home \
      --shell /bin/bash \
${USER}

USER ${USER}

LABEL maintainer="Fabrice P.A. David <fabrice.david@epfl.ch>"
ARG DUMMY=unknown
RUN DUMMY=${DUMMY}
COPY srv /srv
WORKDIR /srv
