# Start from Python 3.12.7 image
FROM python:3.12.7

# System update
RUN apt update && \
    apt upgrade -y && \
    apt install -y git xorg openbox \
    software-properties-common openssl wget \
    net-tools default-jre default-jdk time curl gcc g++ build-essential \
    bison flex \
    libcairo2-dev libcurl4-openssl-dev libssl-dev libxt-dev libtool libharfbuzz-dev libfribidi-dev libpng-dev \
    libtiff5-dev libjpeg-dev libfreetype6 libfreetype-dev libhdf5-dev libxml2-dev libreadline-dev \
    libx11-dev libbz2-dev liblzma-dev libpcre2-dev \
    zlib1g-dev xorg-dev\
    gfortran texinfo texlive

# Define R version
ENV R_VERSION=4.4.3

# Download and build R from source
RUN wget https://cran.r-project.org/src/base/R-4/R-${R_VERSION}.tar.gz && \
    tar -xzf R-${R_VERSION}.tar.gz && \
    cd R-${R_VERSION} && \
    ./configure --enable-R-shlib --with-blas --with-lapack && \
    make -j$(nproc) && \
    make install && \
    cd .. && rm -rf R-${R_VERSION} R-${R_VERSION}.tar.gz

RUN R --version

# Upgrade pip and install Python packages
RUN python -m pip install --no-cache-dir --upgrade pip==24.3.1 setuptools==75.7.0 wheel==0.45.1 cmake==3.14.3 && \
python -m pip install --no-cache-dir --upgrade leidenalg==0.10.2 texttable==1.7.0 igraph==0.11.8 MulticoreTSNE==0.1 anndata==0.11.1 array-api-compat==1.10.0 cffi==1.17.1 click==8.1.8 contourpy==1.3.1 cycler==0.12.1 fonttools==4.55.3 h5py==3.12.1 joblib==1.4.2 kiwisolver==1.4.8 legacy-api-wrap==1.4.1 llvmlite==0.43.0 loompy==3.0.7 matplotlib==3.10.0 natsort==8.4.0 networkx==3.4.2 numba==0.60.0 numpy==2.0.2 numpy-groupies==0.11.2 packaging==24.2 pandas==2.2.3 patsy==1.0.1 pillow==11.1.0 pycparser==2.22 pynndescent==0.5.13 pyparsing==3.2.1 python-dateutil==2.9.0.post0 pytz==2024.2 scanpy==1.10.4 scikit-learn==1.6.0 scipy==1.15.0 seaborn==0.13.2 session-info==1.0.0 six==1.17.0 statsmodels==0.14.4 stdlib_list==0.11.0 threadpoolctl==3.5.0 tqdm==4.67.1 tzdata==2024.2 umap-learn==0.5.7

# Install R packages
#ENV RETICULATE_PYTHON=/usr/local/bin/python
#RUN Rscript -e "install.packages(c('BiocManager', 'Matrix', 'reticulate', 'KernSmooth', 'nlme', 'MASS', 'MAST', 'sanon', 'R6', 'bit64', 'Rtsne', 'jsonlite', 'data.table', 'devtools', 'flexmix', 'rPython', 'statmod', 'plotly', 'future.apply', 'Seurat', 'SeuratObject', 'hdf5r'), repos='http://stat.ethz.ch/CRAN/')" && \
#Rscript -e "BiocManager::install(c('batchelor', 'multtest', 'sva', 'DESeq2', 'limma', 'cluster', 'Cairo', 'scater', 'SC3', 'XVector', 'scran', 'LoomExperiment', 'SingleCellExperiment', 'harmony'))" && \
#Rscript -e "devtools::install_github(c('grimbough/rhdf5','tallulandrews/M3Drop','cellgeni/sceasy'))" && \
#Rscript -e "devtools::install_github(repo = 'mojaveazure/loomR', ref = 'develop')"

COPY R/packages/install_packages.v8.R /tmp/install_packages.v8.R
COPY R/packages/*.tar.gz /tmp/
RUN Rscript /tmp/install_packages.v8.R
RUN rm /tmp/install_packages.v8.R
RUN rm /tmp/*.tar.gz

# User
ENV USER=rvmuser USER_ID=1006 USER_GID=1006

# Maintainer
LABEL maintainer="Fabrice P.A. David <fabrice.david@epfl.ch>"

# Copy data to image
COPY R /srv
COPY python /srv
COPY java /srv
COPY bin /srv

# Working directory
WORKDIR /srv