FROM r-base:4.3.1

# Set up Debian Bullseye and update
RUN echo 'deb http://deb.debian.org/debian bullseye main' > /etc/apt/sources.list \
    && apt-get update -y \
    && apt-get dist-upgrade -y

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxml2-dev python3 python3-pip python3-dev git \
    libcairo2-dev libxt-dev xorg openbox software-properties-common \
    openssl libcurl4-openssl-dev libssl-dev wget net-tools \
    default-jre default-jdk time curl gcc g++ build-essential \
    libtool bison flex python3-venv

# Set up Python virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

# Upgrade pip, setuptools, and wheel
RUN pip install --no-cache-dir --upgrade pip setuptools wheel

# Install cmake via pip if needed
RUN pip install --upgrade cmake==3.14.3

# Verify cmake installation
RUN cmake --version

# Install Python packages with debugging and custom CMake args
RUN python3 -m pip install --break-system-packages leidenalg umap-learn scikit-learn MulticoreTSNE

#install HDF5

COPY lib/hdf5-1.10.6-linux-centos7-x86_64-shared.tar.gz hdf5.tar.gz 
RUN tar -zxf hdf5.tar.gz
RUN mv /hdf5-1.10.6-linux-centos7-x86_64-shared /hdf5
ENV LD_LIBRARY_PATH=/hdf5/lib/
ENV PATH=$PATH:/hdf5/bin
RUN cd /hdf5/bin && ./h5redeploy -force && cd / && rm hdf5.tar.gz

#Install R packages

RUN Rscript -e "install.packages(c('BiocManager', 'Matrix', 'reticulate', 'KernSmooth', 'nlme', 'MASS', 'sanon'), repos='http://stat.ethz.ch/CRAN/'); \
BiocManager::install(c('multtest'))"
RUN Rscript -e "install.packages(c('R6', 'bit64', 'Rtsne', 'jsonlite', 'data.table', 'devtools', 'flexmix', 'rPython', 'statmod', 'plotly', 'future.apply', 'Seurat'), repos='http://stat.ethz.ch/CRAN/');"

# Install the required packages
RUN apt-get install -y libharfbuzz-dev libfribidi-dev libpng-dev libtiff5-dev libjpeg-dev
RUN apt-get install -y libfreetype6 libfreetype-dev

# Clear broken packages and resolve dependencies
RUN dpkg --configure -a
RUN apt-get install -f

# Update and upgrade packages
RUN apt-get update
RUN apt-get upgrade -y


RUN Rscript -e "install.packages(c('devtools'), repos='http://stat.ethz.ch/CRAN/');"
RUN Rscript -e "install.packages(c('MAST'), repos='http://stat.ethz.ch/CRAN/');"

RUN Rscript -e "devtools::install_github(c('grimbough/rhdf5','tallulandrews/M3Drop'))"
RUN Rscript -e "BiocManager::install(c('sva', 'DESeq2', 'limma', 'cluster', 'Cairo', 'scater', 'SC3', 'XVector', 'scran'));"

ENV RETICULATE_PYTHON=/usr/bin/python3

RUN apt-get -y install python3-loompy
RUN Rscript -e "install.packages(c('sanon'))"
RUN Rscript -e "BiocManager::install(c('batchelor'))"

RUN apt-get -y install libhdf5-dev
RUN Rscript -e "install.packages('hdf5r')"

RUN Rscript -e "BiocManager::install(c('LoomExperiment', 'SingleCellExperiment')); \
devtools::install_github('cellgeni/sceasy')"

RUN apt-get -y install python3-anndata 
RUN python3 -m pip install --break-system-packages scanpy

RUN Rscript -e "install.packages(c('SeuratObject'))"
RUN Rscript -e "devtools::install_github(repo = 'mojaveazure/loomR', ref = 'develop')"

ENV USER=rvmuser USER_ID=1006 USER_GID=1006
# now creating user NO NEED IN LAST INSTALL
RUN groupadd --gid "${USER_GID}" "${USER}" && \
    useradd \
      --uid ${USER_ID} \
      --gid ${USER_GID} \
      --create-home \
      --shell /bin/bash \
${USER}

USER ${USER}

LABEL maintainer="Fabrice P.A. David <fabrice.david@epfl.ch>"
ARG DUMMY=unknown
RUN DUMMY=${DUMMY}

COPY R /srv
COPY python /srv
COPY java /srv
COPY bin /srv

WORKDIR /srv