# Refresh asap_run v6/v6.2 scripts while keeping the v6.1 package stack
# (Seurat 4.4.0, SeuratObject 4.1.4, etc.).
#
# Do NOT rebuild from r-base here: unpinned install.packages('Seurat')
# would pull Seurat 5 and break legacy *.asap.3.R scripts.
#
# Build:
#   docker build -f Dockerfile.v6.2 -t fabdavid/asap_run:v6 .
#   docker tag fabdavid/asap_run:v6 fabdavid/asap_run:v6.2

FROM fabdavid/asap_run:v6.1

USER root

COPY R/*.R /srv/
COPY python/*.py /srv/
COPY java/bin/*.jar /srv/
COPY bin/* /srv/

RUN chmod -R 755 /srv

USER rvmuser
WORKDIR /srv
