# Functions
install.cran <- function(package, version, host="cran.r-project.org") {
  main_url <- paste0("https://", host, "/src/contrib/", package, "_", version, ".tar.gz")
  archive_url <- paste0("https://", host, "/src/contrib/Archive/", package, "/", package, "_", version, ".tar.gz")
 
  tmp_file <- tempfile(fileext = ".tar.gz")

  tryCatch({
      message("Trying to install from main CRAN repository...")
      suppressWarnings(download.file(main_url, tmp_file, mode = "wb"))
      install.packages(tmp_file, repos = NULL, type = "source")
      unlink(tmp_file)
    }, error = function(e) {
      message("First attempt failed: ", e$message)
      message("Trying to install from CRAN archive...")

      tryCatch({
          suppressWarnings(download.file(archive_url, tmp_file, mode = "wb"))
          install.packages(tmp_file, repos = NULL, type = "source")
          unlink(tmp_file)
        }, error = function(e) {
          message("Both installation attempts failed: ", e$message)
		  quit(status = 1)
        })
    })
}

install.bioconductor <- function(package, version, bioconductor_version, source = "bioc"){
  main_url <- paste0("https://www.bioconductor.org/packages/release/",source,"/src/contrib/",package,"_",version,".tar.gz")
  archive_url <- paste0("https://www.bioconductor.org/packages/",bioconductor_version,"/",source,"/src/contrib/Archive/",package,"/",package,"_",version,".tar.gz")
  archive_url_2 <- paste0("https://www.bioconductor.org/packages/",bioconductor_version,"/",source,"/src/contrib/",package,"_",version,".tar.gz")
 
  tmp_file <- tempfile(fileext = ".tar.gz")

  tryCatch({
      message("Trying to install from main Bioconductor repository...")
      suppressWarnings(download.file(main_url, tmp_file, mode = "wb"))
      install.packages(tmp_file, repos = NULL, type = "source")
      unlink(tmp_file)
    }, error = function(e) {
      message("First attempt failed: ", e$message)
      message("Trying to install from Bioconductor archive...")

      tryCatch({
          suppressWarnings(download.file(archive_url, tmp_file, mode = "wb"))
          install.packages(tmp_file, repos = NULL, type = "source")
          unlink(tmp_file)
        }, error = function(e) {
		  message("Second attempt failed: ", e$message)
		  message("Trying to install from Bioconductor archive 2...")

		  tryCatch({
			  suppressWarnings(download.file(archive_url_2, tmp_file, mode = "wb"))
			  install.packages(tmp_file, repos = NULL, type = "source")
			  unlink(tmp_file)
			}, error = function(e) {
			  message("3 installation attempts failed: ", e$message)
			  quit(status = 1)
			})
        })
    })
}

install.github <- function(package, version, bioconductor_version, source = "bioc"){ # Suppose it's already downloaded (for safety)
  main_url <- paste0("/tmp/",package,"_",version,".tar.gz") # Copied to /tmp/ by Dockerfile COPY prior running this script
  install.packages(main_url, repos = NULL, type = "source")
}

# CRAN packages
install.cran("rlang", version="1.1.5")
install.cran("Rcpp", version="1.0.14")
install.cran("RcppArmadillo", version="14.2.3-1")
install.cran("bitops", version="1.0-9")
install.cran("Rtsne", version="0.17")
install.cran("MASS", version="7.3-65")
install.cran("RColorBrewer", version="1.1-3")
install.cran("colorspace", version="2.1-1")
install.cran("munsell", version="0.5.1")
install.cran("cli", version="3.6.4")
install.cran("glue", version="1.8.0")
install.cran("lifecycle", version="1.0.4")
install.cran("gtable", version="0.3.6")
install.cran("digest", version="0.6.37")
install.cran("fastmap", version="1.2.0")
install.cran("cachem", version="1.1.0")
install.cran("memoise", version="2.0.1")
install.cran("base64enc", version="0.1-3")
install.cran("htmltools", version="0.5.8.1")
install.cran("pkgconfig", version="2.0.3")
install.cran("magrittr", version="2.0.3")
install.cran("lazyeval", version="0.2.2")
install.cran("fansi", version="1.0.6")
install.cran("vctrs", version="0.6.5")
install.cran("utf8", version="1.2.4")
install.cran("pillar", version="1.10.1")
install.cran("tibble", version="3.2.1")
install.cran("stringi", version="1.8.4")
install.cran("stringr", version="1.5.1")
install.cran("plyr", version="1.8.9")
install.cran("reshape2", version="1.4.4")
install.cran("R6", version="2.6.1")
install.cran("plogr", version="0.2.0")
install.cran("BH", version="1.87.0-1")
install.cran("labeling", version="0.4.3")
install.cran("farver", version="2.1.2")
install.cran("viridisLite", version="0.4.2")
install.cran("scales", version="1.3.0")
install.cran("pheatmap", version="1.0.12")
install.cran("isoband", version="0.2.7")
install.cran("withr", version="3.0.2")
install.cran("ggplot2", version="3.5.1")
install.cran("gridExtra", version="2.3")
install.cran("viridis", version="0.6.5")
install.cran("jsonlite", version="1.9.1")
install.cran("yaml", version="2.3.10")
install.cran("xfun", version="0.51")
install.cran("highr", version="0.11")
install.cran("evaluate", version="1.0.3")
install.cran("knitr", version="1.50")
install.cran("jquerylib", version="0.1.4")
install.cran("fs", version="1.6.5")
install.cran("rappdirs", version="0.3.3")
install.cran("sass", version="0.4.9")
install.cran("mime", version="0.12")
install.cran("bslib", version="0.9.0")
install.cran("fontawesome", version="0.5.3")
install.cran("tinytex", version="0.56")
install.cran("rmarkdown", version="2.29")
install.cran("htmlwidgets", version="1.6.4")
install.cran("png", version="0.1-8")
install.cran("modeltools", version="0.2-23")
install.cran("flexmix", version="2.3-20")
install.cran("mvtnorm", version="1.3-3")
install.cran("DEoptimR", version="1.1-3-1")
install.cran("robustbase", version="0.99-4-1")
install.cran("mgcv", version="1.9-1")
install.cran("nlme", version="3.1-167")
install.cran("iterators", version="1.0.14")
install.cran("foreach", version="1.5.2")
install.cran("lattice", version="0.22-6")
install.cran("matrixStats", version="1.5.0")
install.cran("irlba", version="2.3.5.1")
install.cran("cpp11", version="0.5.2")
install.cran("igraph", version="2.1.4")
install.cran("cluster", version="2.1.8.1")
install.cran("data.table", version="1.17.0")
install.cran("backports", version="1.5.0")
install.cran("Formula", version="1.2-5")
install.cran("checkmate", version="2.3.2")
install.cran("rstudioapi", version="0.17.1")
install.cran("htmlTable", version="2.4.3")
install.cran("Hmisc", version="5.2-3")
install.cran("later", version="1.4.1")
install.cran("promises", version="1.3.2")
install.cran("httpuv", version="1.6.15")
install.cran("xtable", version="1.8-4")
install.cran("sourcetools", version="0.1.7-1")
install.cran("crayon", version="1.5.3")
install.cran("commonmark", version="1.9.2")
install.cran("shiny", version="1.10.0")
install.cran("gtools", version="3.9.5")
install.cran("doParallel", version="1.0.17")
install.cran("caTools", version="1.18.3")
install.cran("gplots", version="3.2.0")
install.cran("ROCR", version="1.0-11")
install.cran("blob", version="1.2.4")
install.cran("WriteXLS", version="6.7.0")
install.cran("brew", version="1.0-10")
install.cran("survival", version="3.8-3")
install.cran("DBI", version="1.2.3")
install.cran("rngtools", version="1.5.2")
install.cran("foreign", version="0.8-88")
install.cran("bit", version="4.6.0")
install.cran("XML", version="3.99-0.18")
install.cran("nnet", version="7.3-20")
install.cran("locfit", version="1.5-9.12")
install.cran("bit64", version="4.6.0-1")
install.cran("RSQLite", version="2.3.9")
install.cran("doRNG", version="1.8.6.1")
install.cran("beeswarm", version="0.4.0")
install.cran("proxy", version="0.4-27")
install.cran("e1071", version="1.7-16")
install.cran("statmod", version="1.5.0")
install.cran("pcaPP", version="2.0-5")
install.cran("Matrix", version="1.7-3")
install.cran("RcppEigen", version="0.3.4.0.2")
install.cran("rrcov", version="1.7-6")
install.cran("KernSmooth", version="2.23-26")
install.cran("vipor", version="0.4.7")
install.cran("codetools", version="0.2-20")
install.cran("rpart", version="4.1.24")
install.cran("class", version="7.3-23")
install.cran("Cairo", version="1.6-2")
install.cran("ggbeeswarm", version="0.7.2")
install.cran("whisker", version="0.4.1")
install.cran("curl", version="6.2.1")
install.cran("sys", version="3.4.3")
install.cran("askpass", version="1.2.1")
install.cran("openssl", version="2.3.2")
install.cran("httr", version="1.4.7")
install.cran("generics", version="0.1.3")
install.cran("tidyselect", version="1.2.1")
install.cran("dplyr", version="1.1.4")
install.cran("ggrepel", version="0.9.6")
install.cran("clipr", version="0.8.0")
install.cran("desc", version="1.4.3")
install.cran("credentials", version="2.0.2")
install.cran("zip", version="2.3.2")
install.cran("purrr", version="1.0.4")
install.cran("rprojroot", version="2.0.4")
install.cran("gitcreds", version="0.1.2")
install.cran("httr2", version="1.1.1")
install.cran("ini", version="0.3.1")
install.cran("gh", version="1.4.1")
install.cran("gert", version="2.1.4")
install.cran("usethis", version="3.1.0")
install.cran("ellipsis", version="0.3.2")
install.cran("miniUI", version="0.1.1.1")
install.cran("profvis", version="0.4.0")
install.cran("ps", version="1.9.0")
install.cran("processx", version="3.8.6")
install.cran("callr", version="3.7.6")
install.cran("pkgbuild", version="1.4.6")
install.cran("pkgload", version="1.4.0")
install.cran("prettyunits", version="1.2.0")
install.cran("sessioninfo", version="1.2.3")
install.cran("xopen", version="1.0.1")
install.cran("rcmdcheck", version="1.4.0")
install.cran("remotes", version="2.5.0")
install.cran("xml2", version="1.3.8")
install.cran("roxygen2", version="7.3.2")
install.cran("rversions", version="2.1.2")
install.cran("urlchecker", version="1.0.1")
install.cran("systemfonts", version="1.2.1")
install.cran("textshaping", version="1.0.0")
install.cran("ragg", version="1.3.3")
install.cran("brio", version="1.1.5")
install.cran("praise", version="1.0.0")
install.cran("diffobj", version="0.3.5")
install.cran("waldo", version="0.6.1")
install.cran("downlit", version="0.4.4")
install.cran("testthat", version="3.2.3")
install.cran("pkgdown", version="2.1.1")
install.cran("devtools", version="2.4.5")
install.cran("sp", version="2.2-0")
install.cran("FNN", version="1.1.4.1")
install.cran("RANN", version="2.6.2")
install.cran("snow", version="0.4-4")
install.cran("formatR", version="1.14")
install.cran("futile.options", version="1.0.1")
install.cran("lambda.r", version="1.2.4")
install.cran("futile.logger", version="1.4.3")
install.cran("boot", version="1.3-31")
install.cran("spatial", version="7.3-18")
install.cran("numDeriv", version="2016.8-1.1")
install.cran("tensorA", version="0.36.2.1")
install.cran("QuickJSR", version="1.6.0")
install.cran("inline", version="0.3.21")
install.cran("RcppParallel", version="5.1.10")
install.cran("bdsmatrix", version="1.3-7")
install.cran("distributional", version="0.5.0")
install.cran("StanHeaders", version="2.32.10")
install.cran("rstantools", version="2.4.0")
install.cran("bbmle", version="1.0.25.1")
install.cran("abind", version="1.4-8")
install.cran("posterior", version="1.6.1")
install.cran("loo", version="2.8.0")
install.cran("rstan", version="2.32.7")
install.cran("densEstBayes", version="1.0-2.2")
install.cran("reldist", version="1.7-2")
install.cran("rsvd", version="1.0.5")
install.cran("RcppML", version="0.3.7")
install.cran("RhpcBLASctl", version="0.23-42")
install.cran("cowplot", version="1.1.3")
install.cran("RcppProgress", version="0.4.2")
install.cran("harmony", version="1.2.3")
install.cran("ggrastr", version="1.0.2")
install.cran("RcppAnnoy", version="0.0.22")
install.cran("sitmo", version="2.0.2")
install.cran("dqrng", version="0.4.1")
install.cran("RSpectra", version="0.16-2")
install.cran("uwot", version="0.2.3")
install.cran("tensor", version="1.5")
install.cran("BiocManager", version="1.30.25")
install.cran("crosstalk", version="1.2.1")
install.cran("globals", version="0.16.3")
install.cran("listenv", version="0.9.1")
install.cran("parallelly", version="1.42.0")
install.cran("future", version="1.34.0")
install.cran("future.apply", version="1.11.3")
install.cran("spatstat.utils", version="3.1-3")
install.cran("spatstat.data", version="3.1-6")
install.cran("spatstat.univar", version="3.1-2")
install.cran("spatstat.sparse", version="3.1-0")
install.cran("goftest", version="1.2-3")
install.cran("deldir", version="2.0-4")
install.cran("polyclip", version="1.10-7")
install.cran("spatstat.geom", version="3.3-5")
install.cran("spatstat.random", version="3.3-2")
install.cran("spatstat.explore", version="3.3-4")
install.cran("hdf5r", version="1.3.12")
install.cran("RcppTOML", version="0.2.3")
install.cran("RcppHNSW", version="0.6.0")
install.cran("dotCall64", version="1.2")
install.cran("spam", version="2.11-1")
install.cran("here", version="1.0.1")
install.cran("pbapply", version="1.7-2")
install.cran("fitdistrplus", version="1.2-2")
install.cran("zoo", version="1.8-13")
install.cran("lmtest", version="0.9-40")
install.cran("progressr", version="0.15.1")
install.cran("ica", version="1.0-3")
install.cran("sanon", version="1.6")
install.cran("leidenbase", version="0.1.32")
install.cran("fastDummies", version="1.7.5")
install.cran("ggridges", version="0.5.6")
install.cran("patchwork", version="1.3.0")
install.cran("reticulate", version="1.44.1") # Fixed that to avoid reticulate warning when using rpy2
install.cran("tidyr", version="1.3.1")
install.cran("scattermore", version="1.2")
install.cran("sctransform", version="0.4.1")
install.cran("plotly", version="4.10.4")
install.cran("leiden", version="0.4.3.1")
#install.cran("SeuratObject", version="4.1.4") # Old version. Because v5 changes too many things.
#install.cran("Seurat", version="4.4.0") # Old version. Because v5 changes too many things.
install.cran("SeuratObject", version="5.2.0")
install.cran("Seurat", version="5.3.1")
install.cran("hms", version="1.1.4")
install.cran("progress", version="1.2.3")
install.cran("tzdb", version="0.5.0")
install.cran("vroom", version="1.6.7")
install.cran("readr", version="2.1.6")
install.cran("hexbin", version="1.28.5")

#Bioconductor packages
install.bioconductor("limma", version="3.62.2", "3.20")
install.bioconductor("edgeR", version="4.4.2", "3.20")
install.bioconductor("BiocGenerics", version="0.52.0", "3.20")
install.bioconductor("Biobase", version="2.66.0", "3.20")
install.bioconductor("S4Vectors", version="0.44.0", "3.20")
install.bioconductor("BiocParallel", version="1.40.0", "3.20")
install.bioconductor("IRanges", version="2.40.1", "3.20")
install.bioconductor("zlibbioc", version="1.52.0", "3.20") # deprecated in 3.22
install.bioconductor("XVector", version="0.46.0", "3.20")
install.bioconductor("GenomeInfoDbData", version="1.2.13", "3.20", "data/annotation")
install.bioconductor("UCSC.utils", version="1.2.0", "3.20")
install.bioconductor("GenomeInfoDb", version="1.42.3", "3.20")
install.bioconductor("GenomicRanges", version="1.58.0", "3.20")
install.bioconductor("MatrixGenerics", version="1.18.1", "3.20")
install.bioconductor("S4Arrays", version="1.6.0", "3.20")
install.bioconductor("SparseArray", version="1.6.2", "3.20")
install.bioconductor("DelayedArray", version="0.32.0", "3.20")
install.bioconductor("SummarizedExperiment", version="1.36.0", "3.20")
install.bioconductor("Biostrings", version="2.74.1", "3.20")
install.bioconductor("KEGGREST", version="1.46.0", "3.20")
install.bioconductor("AnnotationDbi", version="1.68.0", "3.20")
install.bioconductor("annotate", version="1.84.0", "3.20")
install.bioconductor("genefilter", version="1.88.0", "3.20")
install.bioconductor("DESeq2", version="1.46.0", "3.20")
install.bioconductor("sva", version="3.54.0", "3.20")
install.bioconductor("SingleCellExperiment", version="1.28.1", "3.20")
install.bioconductor("SC3", version="1.34.0", "3.20")
install.bioconductor("BiocVersion", version="3.20.0", "3.20")
install.bioconductor("ScaledMatrix", version="1.14.0", "3.20")
install.bioconductor("assorthead", version="1.0.1", "3.20")
install.bioconductor("beachmat", version="2.22.0", "3.20")
install.bioconductor("BiocSingular", version="1.22.0", "3.20")
install.bioconductor("BiocIO", version="1.16.0", "3.20")
install.bioconductor("BiocNeighbors", version="2.0.1", "3.20")
install.bioconductor("scuttle", version="1.16.0", "3.20")
install.bioconductor("scater", version="1.34.1", "3.20")
install.bioconductor("bluster", version="1.16.0", "3.20")
install.bioconductor("metapod", version="1.14.0", "3.20")
install.bioconductor("scran", version="1.34.0", "3.20")
install.bioconductor("multtest", version="2.62.0", "3.20")
install.bioconductor("Rhdf5lib", version="1.28.0", "3.20")
install.bioconductor("rhdf5filters", version="1.18.1", "3.20")
install.bioconductor("rhdf5", version="2.50.2", "3.20")
install.bioconductor("HDF5Array", version="1.34.0", "3.20")
install.bioconductor("LoomExperiment", version="1.24.0", "3.20")
install.bioconductor("sparseMatrixStats", version="1.18.0", "3.20")
install.bioconductor("DelayedMatrixStats", version="1.28.1", "3.20")
install.bioconductor("ResidualMatrix", version="1.16.0", "3.20")
install.bioconductor("batchelor", version="1.22.0", "3.20")

# Git packages (copied locally for ensuring long-term compatibility)
install.github("sceasy", version="0.0.7")
install.github("loomR", version="0.2.1.9000")
install.github("M3Drop", version="3.10.6")
install.github("BPCells", version="0.3.1")
